# Generated by Django 4.0.4 on 2022-06-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateResolved',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
