# Generated by Django 4.0.4 on 2022-06-22 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.sprint'),
            preserve_default=False,
        ),
    ]
