# Generated by Django 4.0.4 on 2022-06-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_ticket_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
