# Generated by Django 4.0.4 on 2022-06-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_ticket_sprint'),
        ('projects', '0004_remove_ticket_assigned_to_ticket_assigned_to'),
    ]

    operations = [
    ]
