# Generated by Django 4.0.4 on 2022-06-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20220623_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='milestone',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Final')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Entry'), (1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Lead')], default=0),
        ),
    ]
