# Generated by Django 4.0.4 on 2022-06-24 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_sprint_milestone_alter_ticket_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sprint',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.sprint'),
        ),
    ]
